### ISSUE TITLE
Configurar SonarQube e TravisCI

### ISSUE THREAD

**Issue by gustavosotnas** [DroidFoundry/DroidMetronome#103]
É uma exigência do prof. Msc. Marcelo Ricardo Quinta pra entrega do trabalho.

**Comment by RenanOfugi** [comment]
Configurei o Sonar e o Travis na PR #102. Para rodar o SonarQube localmente no seu computador:

1. Baixe o SonarQube [aqui](http://www.sonarqube.org/downloads) e o SonarQube Scanner [aqui](http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner);
2. Extraia os dois arquivos .zips;
3. Na pasta do SonarQube, vá em `bin` e depois na pasta correspondente ao sistema operacional que você estiver usando (no meu caso, `linux-x86-64`).
4. Abra um terminal nesta pasta e execute o comando:
```
./sonar.sh start
```
5. Agora vá na pasta-raíz do projeto e abra um terminal nela. Execute o Sonar Scanner com o caminho da pasta onde você o colocou. Por exemplo:
```
/home/gustavosotnas/Downloads/Instaladores/ZIPs/sonar-scanner-2.8/bin/sonar-scanner
```
6. Aguarde o escaneamento e depois entre no navegador no endereço `localhost:9000` que você verá os resultados do escaneamento.

**Obs.:** A execução do Sonar Scanner pode necessitar de privilégios (root).

**Comment by juliannyas** [comment]
Configuração do Travis CI foi realizada na PR #100 .

**Comment by juliannyas** [comment]
Configuração do SonarQube foi realizada na PR #107
