### ISSUE TITLE
FC ao parar metrônomo

### ISSUE THREAD

**Issue by gustavosotnas** [DroidFoundry/DroidMetronome#86]
O aplicativo fecha sozinho (Force Close) ao apertar o botão de Parar durante a execução do metrônomo. Essa falha foi detectada em dois dispositivos Android 4.4 (KitKat) com telas de resolução **HDPI**.

**Comment by PedroDrim** [comment]
## Análise de viabilidade e riscos

#### Atributo 1: Áreas do produto afetadas

| Atributo quanto ao risco no produto          | Definição |Valor   |
|----------------------------------------|------|--------|
|    Mudança em funções **essenciais**   | Componente de software cuja existência é de vital importância para o produto     |   3    |
|    Mudança em funções **secundárias**  | Componente cuja existência é importante para o produto porém a sua falta não afeta a qualidade do sistema      |   2    |
|    Mudança em funções **opcionais**    | Uma modificação que afeta áreas triviais no produto     |   2    |

##### Resultado estipulado ao atributo "Áreas do produto afetadas": 3

#### Atributo 2: Tipo de mudança

| Atributo quanto ao tipo de mudança | Valor da medida |
|----------------------------------------|---------|
|    Correção (A funcionalidade não funciona conforme o esperado) |   3    |
|    Melhoria (A funcionalidade será otimizada)  |   2    |
|    Acréscimo (Uma nova funcionalidade será implementada) |   1    |

##### Resultado estipulado ao atributo "Tipo de mudança": 3

#### Atributo 3: Tempo necessário

| Atributo quanto ao tempo necessário | Critério de avaliação | Valor da medida |
|--------------------------|------------|---------|
|    Curto                 | Entre 1 e 3 horas |  4   |
|    Médio                 | Entre 4 e 7 horas |   3    |
|    Longo                 | Acima de 7 horas |   2    |
|    Atrasado              | Tempo expirado | 1 |

##### Resultado estipulado ao atributo "Tempo necessário": 3

#### Atributo 4: Custo financeiro

|    Custo financeiro da mudança  | Critério de avaliação | Valor total |
|----------------------------------|------|-------------|
|    Sem custo                     |   0 R$   | 4 |
|    Baixo custo                   | Entre de 1 R$ e 1000 R$     |     3       |
|    Médio custo                   | Entre de 1000 R$ e 1500 R$    |   2     |
|    Alto custo                    | Entre de 1500 R$ e 20% do custo do projeto     |   1    |
|    Altíssimo custo               | Acima de 20% do custo do projeto | 0 |

##### Resultado estipulado ao atributo "Custo financeiro": 4

#### Classificação final

A classificação final da Análise de Viabilidade e Riscos é dada pelo produto dos resultados obtidos nos atributos acima, conforme a tabela abaixo:

| Classificação       | Valor total  |
|---------------------|--------------|
| Viável              |   81 - 144   |
| Parcialmente Viável |   48 - 80    |
| Dificilmente Viável |   24 - 47    |
| Inviável            | abaixo de 24 |  

##### Resultado da Análise de Viabilidade e Risco: 108

##  Análise de impacto

### Descrição da manutenção: 

Alterar API do botão usada, para a API padrão do google design support

### Áreas modificadas:

Desenvolvimento.

### Outras áreas afetadas:

Gerência de configuração, verificação e validação.
